use_alpha_beta: true
use_imu: false
use_odom: false
use_vel: false
max_iterations: 10
max_correspondence_dist: 0.3
max_angular_correction_deg: 45.0
max_linear_correction: 0.5
epsilon_xy: 0.000001
epsilon_theta: 0.000001
outliers_max_percent: 0.85
sigma: 0.01
use_corr_tricks: true
restart: false
restart_threshold_mean_error: 0.01
restart_dt: 1.0
restart_dtheta: 0.1
clustering_threshold: 0.25
orientation_neighbourhood: 20
use_point_to_line_distance: true
do_alpha_test: true
do_alpha_test_thresholdDeg: 20.0
outliers_adaptive_order: 0.7
outliers_adaptive_mult: 2.0
do_visibility_test: true
allowable_gap_count: 5
do_compute_covariance: true
skip_threshold: 0.0
laser_frame: laser
base_frame: base_link
fixed_frame: odom
publish_tf: true
publish_pose: true
publish_pose_stamped: true
publish_pose_with_covariance: true
publish_pose_with_covariance_stamped: true
